name: fitm

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, curl, mysql

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install PHP dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest

    - name: Install NPM dependencies and build assets
      run: |
        npm install
        npm run build

    - name: Run Laravel tests
      run: php artisan test

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 2299
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 18 || nvm install 18
          
          cd /var/www/fitm
          git pull origin release
          composer install --no-dev
          npm install
          npm run build
          php artisan optimize:clear
